Repository DDD-Community/DDD-12-Darayo-iOS, pull requests merged in 2025-07, with the labels that each got.

#15 [Feat] 앱 진입 화면 UI 구현
  Projects/DesignSystem/Derived/Sources/TuistImages+DesignSystem.swift
  Projects/DesignSystem/Resources/Images.xcassets/icon_bell.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/icon_bell.imageset/icon_bell.pdf
  Projects/DesignSystem/Resources/Images.xcassets/icon_picture.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/icon_picture.imageset/icon_picture.pdf
  Projects/Features/Root/Sources/Main/MainFeature.swift
  Projects/Features/Root/Sources/Main/MainView.swift
  Projects/Features/Root/Sources/Permission/PermissionFeature.swift
  Projects/Features/Root/Sources/Permission/PermissionView.swift
  Projects/Features/Root/Sources/Root/RootFeature.swift
  Projects/Features/Root/Sources/Root/RootView.swift
  Projects/Features/Root/Sources/RootFeature.swift
  Projects/Features/Root/Sources/RootView.swift
  Projects/Features/Root/Sources/Splash/SplashFeature.swift
  Projects/Features/Root/Sources/Splash/SplashView.swift
Labels: ✨ 기능추가

#23 [Feat] 타임테이블 탭 화면 UI 구현
  Projects/DesignSystem/Derived/Sources/TuistImages+DesignSystem.swift
  Projects/DesignSystem/Resources/Images.xcassets/icon_chevron_left.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/icon_chevron_left.imageset/icon_chevron_left.pdf
  Projects/DesignSystem/Resources/Images.xcassets/icon_down.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/icon_down.imageset/icon_down.pdf
  Projects/DesignSystem/Resources/Images.xcassets/icon_download.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/icon_download.imageset/icon_download.pdf
  Projects/DesignSystem/Resources/Images.xcassets/icon_filter.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/icon_filter.imageset/icon_filter.pdf
  Projects/DesignSystem/Sources/Timetable/TimetableView.swift
  Projects/Features/Timetable/Sources/TimetableFeature.swift
  Projects/Features/Timetable/Sources/TimetableView.swift
Labels: ✨ 기능추가

#33 [Feat] 타임테이블 화면 Bottom Sheet UI구현
  Projects/DesignSystem/Derived/Sources/TuistImages+DesignSystem.swift
  Projects/DesignSystem/Resources/Images.xcassets/icon_artist_placeholder_selected.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/icon_artist_placeholder_selected.imageset/icon_artist_placeholder_selected.pdf
  Projects/DesignSystem/Resources/Images.xcassets/icon_close.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/icon_close.imageset/icon_close.pdf
  Projects/Domain/Sources/Models/Artist.swift
  Projects/Features/Timetable/Sources/SelectArtist/SelectArtistFeature.swift
  Projects/Features/Timetable/Sources/SelectArtist/SelectArtistView.swift
  Projects/Features/Timetable/Sources/SelectFestival/SelectFestivalFeature.swift
  Projects/Features/Timetable/Sources/SelectFestival/SelectFestivalView.swift
  Projects/Features/Timetable/Sources/Timetable/TimetableFeature.swift
  Projects/Features/Timetable/Sources/Timetable/TimetableView.swift
  Projects/Features/Timetable/Sources/TimetableFeature.swift
Labels: ✨ 기능추가

#41 [Feat] MY탭 이용약관
  Projects/DesignSystem/Sources/Gradient/Gradient.swift
  Projects/DesignSystem/Sources/Navigation/Navigation.swift
  Projects/Features/MyPage/Sources/TermsOfService/TermsOfServiceFeature.swift
  Projects/Features/MyPage/Sources/TermsOfService/TermsOfServiceView.swift
  Projects/Features/Root/Sources/Main/MainFeature.swift
  Projects/Util/Resources/Text/TermsOfService.txt
  Projects/Util/Sources/Constant/Constant.swift
  Projects/Util/Sources/Constants/URLConstant.swift
  Projects/Util/Sources/Extensions/Bundle+.swift
  Tuist/ProjectDescriptionHelpers/Target.swift
Labels: ✨ 기능추가

#43 [Feat] MY탭 개인정보 처리방침
  Projects/Features/MyPage/Sources/PrivacyPolicy/PrivacyPolicyFeature.swift
  Projects/Features/MyPage/Sources/PrivacyPolicy/PrivacyPolicyView.swift
  Projects/Util/Resources/Text/PrivacyPolicy.txt
  Projects/Util/Sources/Constant/Constant.swift
Labels: ✨ 기능추가

#48 [Feat] 앱 아이콘, 로고 추가
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Group 24.png
  Projects/App/Resources/Assets.xcassets/LaunchScreen.colorset/Contents.json
  Projects/DesignSystem/Derived/Sources/TuistColors+DesignSystem.swift
  Projects/DesignSystem/Derived/Sources/TuistImages+DesignSystem.swift
  Projects/DesignSystem/Resources/Colors.xcassets/GradientSplash1.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/GradientSplash2.colorset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/character_splash.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/character_splash.imageset/character_splash.pdf
  Projects/DesignSystem/Resources/Images.xcassets/logo.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/logo.imageset/logo.pdf
  Projects/DesignSystem/Resources/Images.xcassets/logo_splash.imageset/Contents.json
  Projects/DesignSystem/Resources/Images.xcassets/logo_splash.imageset/logo_splash.pdf
  Projects/Features/Home/Sources/Home/HomeView.swift
  Projects/Features/Root/Sources/Splash/SplashView.swift
  Tuist/ProjectDescriptionHelpers/ProjectInfo.swift
Labels: ✨ 기능추가

#64 refactor: clipShape 중복 적용 삭제
  Projects/DesignSystem/Sources/Calendar/EventCard.swift
Labels: ♻️ 리팩토링

#60 [Feat] 페스티벌 조회 API 구현
  Projects/App/Sources/DI.swift
  Projects/Data/Sources/Endpoints/AuthEndpoint.swift
  Projects/Data/Sources/Endpoints/Endpoint.swift
  Projects/Data/Sources/Endpoints/FestivalEndpoint.swift
  Projects/Data/Sources/Repositories/FestivalRepository.swift
  Projects/Data/Sources/Responses/FestivalResponse.swift
  Projects/DesignSystem/Sources/Shimmer/Shimmer.swift
  Projects/Domain/Sources/Models/Festival.swift
  Projects/Domain/Sources/RepositoryProtocols/FestivalRepositoryProtocol.swift
  Projects/Domain/Sources/UseCases/FestivalUseCase.swift
  Projects/Features/Home/Sources/Home/Components/FestivalGridView.swift
  Projects/Features/Home/Sources/Home/HomeFeature.swift
  Projects/Features/Home/Sources/Home/HomeGridView.swift
  Projects/Features/Home/Sources/Home/HomeView.swift
  Projects/Util/Sources/Constant/DateFormat.swift
  Projects/Util/Sources/Extensions/Date+.swift
  Projects/Util/Sources/Extensions/String+.swift
Labels: ✨ 기능추가

#72 [Feat] 페스티벌 좋아요 기능 구현
  Projects/App/Sources/DI.swift
  Projects/App/Sources/FestibeeApp.swift
  Projects/Data/Sources/PersistentData/LikedFestival.swift
  Projects/Data/Sources/Repositories/FestivalRepository.swift
  Projects/Data/Sources/ServiceProtocols/PersistentDataServiceProtocol.swift
  Projects/Domain/Sources/Models/LikedFestival.swift
  Projects/Domain/Sources/RepositoryProtocols/FestivalRepositoryProtocol.swift
  Projects/Domain/Sources/UseCases/FestivalUseCase.swift
  Projects/Features/Home/Sources/Festival/FestivalFeature.swift
  Projects/Features/Home/Sources/Home/HomeFeature.swift
  Projects/Features/Root/Sources/Main/MainFeature.swift
  Projects/Persistence/Project.swift
  Projects/Persistence/Sources/PersistentDataService/PersistentDataService.swift
  Tuist/ProjectDescriptionHelpers/Dependency.swift
  Tuist/ProjectDescriptionHelpers/Module.swift
Labels: ✨ 기능추가

#74 [Fix] Splash UI 수정
  Projects/DesignSystem/Resources/Images.xcassets/logo_splash.imageset/logo_splash.pdf
  Projects/Features/Root/Sources/Splash/SplashView.swift
Labels: 🛠️ 기타수정

#77 [Feat] Calendar뷰 정보 조회
  Projects/DesignSystem/Sources/Calendar/CalendarDayCell.swift
  Projects/DesignSystem/Sources/Calendar/CalendarModel.swift
  Projects/DesignSystem/Sources/Calendar/CalendarView.swift
  Projects/DesignSystem/Sources/Calendar/DummyEventData.swift
  Projects/DesignSystem/Sources/Calendar/EventCard.swift
  Projects/Domain/Sources/Models/Reservation.swift
  Projects/Features/Home/Sources/Home/Components/EventListView.swift
  Projects/Features/Home/Sources/Home/HomeCalendarView.swift
  Projects/Features/Home/Sources/Home/HomeView.swift
  Projects/Util/Sources/Constant/DateFormat.swift
Labels: ✨ 기능추가

#84 [Fix] 앱 아이콘 수정
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon.png
Labels: 🛠️ 기타수정

#86 [Feat] 알림 설정 페스티벌 목록 상세페이지 이동
  Projects/Features/MyPage/Sources/NotificationSetting/NotificationSettingFeature.swift
  Projects/Features/MyPage/Sources/NotificationSetting/NotificationSettingView.swift
  Projects/Features/MyPage/Sources/NotificationSetting/SubscribedFestivalListView.swift
  Projects/Features/Root/Sources/Main/MainFeature.swift
Labels: ✨ 기능추가

#89 [Fix] 이용 약관, 개인정보 처리방침 수정
  Projects/Util/Resources/Text/PrivacyPolicy.txt
  Projects/Util/Resources/Text/TermsOfService.txt
Labels: 🛠️ 기타수정

#90 [FSTB-98] 푸시 발송 안되는 이슈 (iOS)
  Projects/App/Sources/AppDelegate.swift
Labels: 🧩 버그수정
